# name: Deploy Nginx on EC2

# on:
#   workflow_dispatch:
#     inputs:
#       Run it:
#         description: Installing Nginx On EC2
#         required: true
        
# jobs:
#   deploy-nginx:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install pip
#         run: python -m ensurepip --default-pip

#       - name: Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install -y python3-pip
#           sudo pip3 install ansible

#       - name: Clear Known Hosts File
#         run: rm -f ~/.ssh/known_hosts
        
#       - name: Set up SSH Key
#         run: |
#           mkdir -p /home/runner/.ssh/
#           echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
#           chmod 400 /home/runner/.ssh/id_rsa
#         shell: bash

#       - name: Display SSH Key
#         run: cat ~/.ssh/id_rsa


#       - name: Add EC2 Host Key
#         run: ssh-keyscan -H -t rsa 13.201.121.161 >> ~/.ssh/known_hosts
  
#       - name: Display SSH Key and Known Hosts
#         run: |
#           cat ~/.ssh/id_rsa
#           cat ~/.ssh/known_hosts

#       - name: Run Ansible Playbook
#         run: |
#           ansible-playbook -i inventory.ini --private-key=/home/runner/.ssh/id_rsa -u ubuntu -b nginx-playbook.yml




name: Install Nginx
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
 
    - name: Install Ansible
      run: |
        pip install ansible
      continue-on-error: true
 
    - name: Set up SSH Key
      run: |
        mkdir -p /home/runner/.ssh/
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
      shell: bash
 
    - name: Run Ansible playbook
      run: |
        ansible-playbook -i inventory.ini --private-key=/home/runner/.ssh/id_rsa -u ubuntu -b nginx-playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: false













# name: Ansible Deployment
# on:
#   workflow_dispatch:
#     inputs:
#       Run:
#         description: 'Ansible-github'
#         required: true  # Change to your default branch name if different
# jobs:
#   deploy:
#     runs-on: ubuntu-latest  # Use the latest Ubuntu runner
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'  # Change to your Python version if different
#     - name: Install Ansible
#       run: |
#         pip install ansible
#     - name: Deploy with Ansible
#       run: |
#         ansible-playbook -i inventory.ini playbook.yml



# name: Install Nginx
# on:
#   workflow_dispatch:
# jobs:
#   install_nginx:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'
#       - name: Update apt Package and Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install ansible
         # python -m pip install --upgrade pip
          # pip install ansible
 
      # - name: Set up Private SSH key
      #   run: |
      #     mkdir -p /home/runner/.ssh
      #     echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
      #     chmod 600 /home/runner/.ssh/id_rsa
 
      # - name: Ping Node
      #   run: |
      #     ansible -i "3.110.187.195" -u ubuntu --private-key=/home/runner/.ssh/id_rsa -m ping
 
      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook -i inventory.ini nginx-install.yml





# name: Install nginx on EC2
# on:
#   workflow_dispatch:
# jobs:
#   Install-nginx:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install pip
#         run: python -m ensurepip --default-pip

#       - name: Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install -y python3-pip
#           sudo pip3 install ansible
        
#       - name: Set up SSH Key
#         run: |
#           mkdir -p /home/runner/.ssh/
#           echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
#           chmod 600 /home/runner/.ssh/id_rsa
        
        
      # - name: Add EC2 Host Key
      #   run: ssh-keyscan -H -t rsa 13.201.121.161 >> ~/.ssh/known_hosts

      # - name: Run Ansible Playbook
      #   run: |
      #     ansible-playbook -i inventory.ini --private-key=/home/runner/.ssh/id_rsa --extra-vars "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" nginx-playbook.yml
