name: Ansible Deployment

on:
  push:
    branches:
      - main  # Change to your default branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Change to your Python version if different

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Deploy with Ansible
      run: |
        ansible-playbook -i inventory.ini playbook.yml
